export const FETCH_POKES_REQUEST = 'FETCH_POKES_REQUEST';
export const FETCH_POKES_ERROR = 'FETCH_POKES_ERROR';
export const FETCH_POKES_SUCCESS = 'FETCH_POKES_SUCCESS';

export const FETCH_POKE_BY_ID_REQUEST = 'FETCH_POKE_BY_ID_REQUEST';
export const FETCH_POKE_BY_ID_SUCCESS = 'FETCH_POKE_BY_ID_SUCCESS';
export const FETCH_POKE_BY_ID_ERROR = 'FETCH_POKE_BY_ID_ERROR';